server:
  port: 8181

spring:
  config:
    activate:
      on-profile: default
  application:
    name: page-service

  liquibase:
    enabled: false
  web:
    resources:
      static-locations: classpath:/static/