server:
  port: 8181

spring:
  liquibase:
    enabled: false

  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

product:
  service:
    url: ${PRODUCT_SERVICE_URL}

cart:
  service:
    url: ${CART_SERVICE_URL}

auth:
  service:
    url: ${AUTH_SERVICE_URL}