server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  config:
    activate:
      on-profile: docker

  application:
    name: product-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

management:
  server:
    port: 8080