server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: product-service
  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml