server:
  port: 8081

spring:
  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml